services:
  db:
    image: postgres:12.7-alpine
    restart: always
    container_name: faraday_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=faraday
    ports:
      - '5432'
    volumes:
      - "db:/var/lib/postgresql/data:rw"
  redis:
    image: 'redis:6.2-alpine'
    container_name: faraday_redis
    ports:
      - '6379'
  change-password:
    image: index.docker.io/faradaysec/faraday
    command: ["faraday-manage", "change-password"]
  faraday-default-worker:
    image: index.docker.io/faradaysec/faraday
    restart: always
    container_name: faraday_worker
    command: [ "faraday-worker" ]
    volumes:
      - "faraday:/home/faraday/.faraday:rw"  # to save or use existent config
      #  - "your_path_to/faraday:/src"  # to use code source with image created with DEV_ENV
    environment:
      - PGSQL_USER=postgres
      - PGSQL_PASSWD=postgres
      - PGSQL_HOST=db
      - PGSQL_DBNAME=faraday
      - REDIS_SERVER=redis
    depends_on:
      faraday-server:
        condition: service_healthy
  faraday-server:
    image: index.docker.io/faradaysec/faraday
    restart: always
    container_name: faraday_server
    entrypoint: "/entrypoint.sh"
    volumes:
      - "faraday:/home/faraday/.faraday:rw"  # to save or use existent config
      #  - "your_path_to/faraday:/src"  # to use code source with image created with DEV_ENV
    environment:
      - PGSQL_USER=postgres
      - PGSQL_PASSWD=postgres
      - PGSQL_HOST=db
      - PGSQL_DBNAME=faraday
      - REDIS_SERVER=redis
    depends_on:
     - db
     - redis
    ports:
     - "5985:5985"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5985/_api/config"]
      interval: 60s
      timeout: 30s
volumes:
  db:
    driver: local
